sudo: required
services:
  - docker

os: linux
dist: bionic
language: minimal

before_install:
  - sudo mkdir /lower /upper /work /cvmfs /cvmfs/sandbox.galaxyproject.org
  - curl -O https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
  #- sudo apt-get update
  #- sudo apt-get install --no-install-recommends -y lsb-release
  - sudo dpkg -i cvmfs-release-latest_all.deb
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y cvmfs
  - sudo cp .ci/default.local /etc/cvmfs
  - sudo cp .ci/sandbox.galaxyproject.org.pub /etc/cvmfs/keys
  - sudo cvmfs_config chksetup || true
  - sudo mount -t cvmfs sandbox.galaxyproject.org /lower || true
  - sudo dmesg | grep cvmfs
  - sudo dmesg | tail
  - sudo cat /tmp/cvmfs.log || true
  - sudo ls /var/log
  - sudo tail /var/log/messages || true
  - sudo tail /var/log/syslog || true
  - travis_terminate 1
  - ls -l /lower
  - sudo mount -t overlay overlay -o lower=/lower,upper=/upper,work=/work /cvmfs/sandbox.galaxyproject.org
  - ls -l /cvmfs/sandbox.galaxyproject.org

script:
  - echo yay
